//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMenu
    {
        public int id { get; set; }
        public string DishName { get; set; }
        public decimal FullPrice { get; set; }
        public decimal DiscoundPrice { get; set; }
    }
}
